minipos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler400 = 'store.views.error_handler_view.handler400'
handler403 = 'store.views.error_handler_view.handler403'
handler404 = 'store.views.error_handler_view.handler404'
handler500 = 'store.views.error_handler_view.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from .views.pos_view import product_order_view, add_order_view, clear_cart_items, cart_updated, order_transaction, remove_cart_item
from .views.product_view import product_view, delete_product, update_product, publish_unpublish_product
from .views.order_view import sales_view, pay_balance, pay_order, sales_details, order_view, accept_order, cancel_order
from .views.customer_view import customer_view, customer_detail_view
from .views.category_view import add_category
from .views.item_request_view import request_item, delete_request, request_product_restock, request_status_update, item_request_view
from .views.user_view import register_user


app_name = 'store'
urlpatterns = [
    path('pos', product_order_view, name='pos_view'),
    path('update-quantity/<bar_code>', cart_updated, name='update_quantity'),
    path('remove-item/<bar_code>', remove_cart_item, name='remove_cart_item'),
    path('sales', sales_view, name='sales_view'),
    path('orders', order_view, name='order_view'),
    path('orders/accept/<order_id>', accept_order, name='accept_order'),
    path('orders/cancel/<order_id>', cancel_order, name='cancel_order'),
    path('add-orders/<pk>', add_order_view, name='add_order'),
    path('orders/clear', clear_cart_items, name='clear_order'),
    path('orders/details/<order_id>', sales_details, name='sales_details'),
    path('orders/balance/<pk>', pay_balance, name='pay_balance'),
    path('orders/pay/<order_id>', pay_order, name='pay_order'),
    path('', product_view, name='product_view'),
    # path('add', add_product, name='add_product_view'),
    path('categories/add', add_category, name='add_category'),
    path('update/<pk>', update_product, name='update_product'),
    path('publish/update/<pk>', publish_unpublish_product, name='publish_unpublish_product'),
    path('delete/<pk>', delete_product, name='delete_product'),
    path('request', item_request_view, name='item_request_view'),
    path('request/item', request_item, name='request_item'),
    path('request/item/restock/<pk>', request_product_restock, name='request_product_restock'),
    path('request/item/delete/<pk>', delete_request, name='delete_request'),
    path('request/item/update/<pk>', request_status_update, name='request_status_update'),
    path('customers', customer_view, name='customer_view'),
    # path('customers/update/<pk>', update_customer, name='update_customer'),
    path('customers/details/<pk>', customer_detail_view, name='customer_details'),
    path('process-order', order_transaction, name='process_order'),
    path('users/registration', register_user, name='register_user'),
]

store/models.py
import uuid
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from PIL import Image
from io import BytesIO
from django.utils import timezone

# Create your models here.
class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated','-created')


class Category(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name

def image_directory_path(instance, filename):
    print(filename)
    return 'images_{0}/{1}'.format(instance, filename)

class Product(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bar_code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    cost = models.FloatField()
    price = models.FloatField()
    quantity = models.IntegerField()
    image = models.ImageField(upload_to=image_directory_path, blank=True, null=True)
    on_display = models.BooleanField(default=True, verbose_name="this product is available?")

    @property
    def total_cost(self):
        total = self.cost * float(self.quantity)
        return total

    def __str__(self):
        return self.name
    

class ProductTransaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cost = models.FloatField(blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-updated']

    @property
    def new_cost(self):
        current_quantity = self.product.quantity
        current_cost = self.product.cost

        new_added_quantity = self.quantity
        new_added_cost = self.cost

        if current_quantity:
            updated_cost = ((current_quantity/(current_quantity + new_added_quantity)) * current_cost) + ((new_added_quantity/(current_quantity + new_added_quantity)) * new_added_cost)
        else:
            updated_cost = new_added_cost
        return updated_cost

    @property
    def total_cost(self):
        total = self.cost * float(self.quantity)
        return total

    def __str__(self):
        return self.product.name

class Customer(models.Model):
    customer_id = models.CharField(max_length=12, unique=True, blank=True, null=True)
    name = models.CharField(max_length=200, unique=True)
    contact = models.CharField(max_length=20, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name
    
class OrderTransaction(models.Model):
    order_id = models.CharField(max_length=12, unique=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.PositiveIntegerField()
    total_amount = models.FloatField()
    is_paid = models.BooleanField(default=False)
    is_accepted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-is_accepted','-created']

    @property
    def get_cost(self):
        cost = self.price * self.quantity
        return cost
    
    @property
    def change(self):
        change = self.total_amount - self.money_tender
        return change
    
    @property
    def balance(self):
        if not self.is_paid:
            balance = self.get_cost
        else:
            balance = 0.0
        return balance
    
    @property
    def is_recent_orders(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created <= now

    def __str__(self):
        return self.customer.username

class CustomerOrder(TimeStampedModel):
    order_id = models.CharField(max_length=100, unique=True)
    orders = models.ForeignKey(OrderTransaction, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.order_id


class ItemRequest(models.Model):
    request_by = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=120)
    message = models.CharField(max_length=120, blank=True, null=True)
    is_noted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.request_by

@receiver(post_save, sender=OrderTransaction)
def order_pro_save(sender, instance, created, *args, **kwargs):
    if created:
        uuid_code = str(uuid.uuid4()).replace("-", "").upper()[:8]
        instance.order_id = uuid_code
        instance.save()

@receiver(pre_save, sender=Customer)
def customer_id_pre_save(sender, instance, *args, **kwargs):
    if instance.customer_id == None:
        uuid_code = str(uuid.uuid4()).replace("-", "").upper()[:12]
        instance.customer_id = uuid_code

@receiver(pre_save, sender=CustomerOrder)
def customer_order_id_pre_save(sender, instance, *args, **kwargs):
    if instance.order_id == None:
        uuid_code = str(uuid.uuid4()).replace("-", "").upper()[:12]
        instance.order_id = uuid_code

templates/includes/greeting.html
<div class="row">
    <div class="col-sm-12">
        <div class="card border-0 shadow-sm mt-3">
            <div class="card-body">
                <h2>Hello {{ request.user.username|title }}!</h2>
            </div>
        </div>
    </div>
</div>

templates/includes/messages.html
{% for message in messages %}
<div class="alert alert-{{ message.tags }} d-flex justify-content-between align-items-center mt-3" role="alert">
    <div>
        {% if instance %}
        <strong>Ta dah! </strong> {{ message|safe }} {% if order %}<a href="{% url 'store:order_details' order.order_id %}">View order</a>{% endif %}
        {% else %}
        <strong>Ta dah! </strong>{{ message|safe }}
        {% endif %}
    </div>
    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

templates/includes/navigation.html
{% load crispy_forms_tags %}

<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #222;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'store:product_view' %}">MINI STORE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'store:product_view' %}">Products</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'store:order_view' %}">Orders</a>
          </li>
          {% if perms.auth.view_ordertransaction %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'store:sales_view' %}">Sales</a>
          </li>
          {% endif %}
          {% if perms.auth.view_user %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'store:customer_view' %}">Customers</a>
          </li>
          {% endif %}
          {% if perms.store.view_itemrequest %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'store:item_request_view' %}">Requested stocks</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:pos_view' %}">Cart {% if cart_items > 1 %}items <span class="badge text-bg-success"> {{ cart_items }}{% else %}item <span class="badge text-bg-secondary"> {{ cart_items }}{% endif %}</span></a>
          </li>
        </ul>
        <ul class="navbar-nav float-end mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link" aria-current="page">Hello {{request.user.username|title}}!</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#" data-bs-toggle="modal" data-bs-target="#logoutUser">Logout</a>
          </li>
          {% endif %}
        </ul>
        <!-- <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
      </div>
    </div>
</nav>

<div class="modal fade" id="addUser" tabindex="-1" aria-labelledby="logoutLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="logoutLabel">Logout</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="POST">
        {% csrf_token %}
      <div class="modal-body">
          {{form|crispy}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary border-0 shadow-sm" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary btn-sm">Add User</button>
      </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="logoutUser" tabindex="-1" aria-labelledby="logoutLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="logoutLabel">Logout</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to logout?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary border-0 shadow-sm" data-bs-dismiss="modal">No</button>
        <a href="{% url 'logout' %}" class="btn btn-outline-primary border-0 shadow-sm">Yes</a>
      </div>
    </div>
  </div>
</div>

templates/includes/scanner.html
<div id="qr-reader" style="width: 600px"></div>

{% block script %}

<script>
    function onScanSuccess(decodedText, decodedResult) {
        console.log(`Code scanned = ${decodedText}`, decodedResult);
    }
    var html5QrcodeScanner = new Html5QrcodeScanner(
        "qr-reader", { fps: 10, qrbox: 250 });
    html5QrcodeScanner.render(onScanSuccess);
</script>

{% endblock %}