minipos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler400 = 'store.views.error_handler_view.handler400'
handler403 = 'store.views.error_handler_view.handler403'
handler404 = 'store.views.error_handler_view.handler404'
handler500 = 'store.views.error_handler_view.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from .views.pos_view import product_order_view, add_order_view, clear_cart_items, cart_updated, order_transaction, remove_cart_item
from .views.product_view import product_view, delete_product, update_product, publish_unpublish_product
from .views.order_view import sales_view, pay_balance, pay_order, sales_details, order_view, accept_order, cancel_order
from .views.customer_view import customer_view, customer_detail_view
from .views.category_view import add_category
from .views.item_request_view import request_item, delete_request, request_product_restock, request_status_update, item_request_view
from .views.user_view import register_user


app_name = 'store'
urlpatterns = [
    path('pos', product_order_view, name='pos_view'),
    path('update-quantity/<bar_code>', cart_updated, name='update_quantity'),
    path('remove-item/<bar_code>', remove_cart_item, name='remove_cart_item'),
    path('sales', sales_view, name='sales_view'),
    path('orders', order_view, name='order_view'),
    path('orders/accept/<order_id>', accept_order, name='accept_order'),
    path('orders/cancel/<order_id>', cancel_order, name='cancel_order'),
    path('add-orders/<pk>', add_order_view, name='add_order'),
    path('orders/clear', clear_cart_items, name='clear_order'),
    path('orders/details/<order_id>', sales_details, name='sales_details'),
    path('orders/balance/<pk>', pay_balance, name='pay_balance'),
    path('orders/pay/<order_id>', pay_order, name='pay_order'),
    path('', product_view, name='product_view'),
    # path('add', add_product, name='add_product_view'),
    path('categories/add', add_category, name='add_category'),
    path('update/<pk>', update_product, name='update_product'),
    path('publish/update/<pk>', publish_unpublish_product, name='publish_unpublish_product'),
    path('delete/<pk>', delete_product, name='delete_product'),
    path('request', item_request_view, name='item_request_view'),
    path('request/item', request_item, name='request_item'),
    path('request/item/restock/<pk>', request_product_restock, name='request_product_restock'),
    path('request/item/delete/<pk>', delete_request, name='delete_request'),
    path('request/item/update/<pk>', request_status_update, name='request_status_update'),
    path('customers', customer_view, name='customer_view'),
    # path('customers/update/<pk>', update_customer, name='update_customer'),
    path('customers/details/<pk>', customer_detail_view, name='customer_details'),
    path('process-order', order_transaction, name='process_order'),
    path('users/registration', register_user, name='register_user'),
]

store/forms/customer_form.py
from django import forms
from store.models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = [
            'name',
            'contact'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
        }

store/forms/order_form.py
from django import forms
from store.models import OrderTransaction


class OrderTransaction(forms.ModelForm):
    class Meta:
        model = OrderTransaction
        fields = [
            'customer',
            'product',
            'price',
            'quantity',
            'money_tender',
            'is_paid'
        ]
        widgets = {
            'customer': forms.TextInput(attrs={'class': 'form-control'}),
            'product': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'money_tender': forms.NumberInput(attrs={'class': 'form-control'}),
            'is_paid': forms.BooleanField(attrs={'class': 'form-control'}),
        }

store/views/category_view.py
from store.models import Category
from django.shortcuts import render, get_object_or_404, redirect
from store.cartitem import Cart
from django.views.decorators.http import require_POST
from django.db.models import Sum, F
from django.contrib.auth.decorators import login_required, permission_required


@login_required
@require_POST
@permission_required("store.add_category", raise_exception=True)
def add_category(request):
    category_name = request.POST.get('categoryName')
    if request.method == 'POST':
        category = Category(
            name = category_name,
        )
        category.save()
        return redirect('store:product_view')

store/views/customer_view.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import OrderTransaction, Customer
from django.contrib.auth.models import User
from store.cartitem import Cart
from django.views.decorators.http import require_POST
from django.db.models import Sum, F, Q
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib import messages

# @login_required
# @require_POST
# def add_customer_view(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         contact = request.POST.get('contact')
#         customer = Customer.objects.create(
#             name=name,
#             contact=contact
#         )
#         customer.save()
#         return redirect('store:pos_view')
    


@login_required
@permission_required("store.view_user", raise_exception=True)
def customer_view(request):
    customers_balance = User.objects.filter(Q(ordertransaction__is_paid=False), Q(ordertransaction__is_accepted=True)).annotate(total_balance=(Sum(F('ordertransaction__price') * F('ordertransaction__quantity'))))
    total_balance = customers_balance.aggregate(balance = Sum('total_balance'))
    customers = User.objects.all()
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.add_message(request, messages.SUCCESS,
                                 'User successfully created name: %s.' % (instance.username.title()))
            return redirect('store:customer_view')
    else:
        form = UserCreationForm(request.POST or None)

    cart = Cart(request)
    cart_items = cart.__len__()

    context = {
        'title': 'customers',
        'customers': customers,
        'customers_balance': customers_balance,
        'cart_items': cart_items,
        'total_balance': total_balance,
        'form': form,
    }
    return render(request, 'customer_view.html', context)

@login_required
@permission_required("store.view_user", raise_exception=True)
def customer_detail_view(request, pk):
    customer = get_object_or_404(User, pk=pk)
    unpaid_orders = OrderTransaction.objects.filter(customer=customer).filter(is_paid=False)
    total_unpaid_orders = unpaid_orders.aggregate(total_unpaid=(Sum(F('price') * F('quantity'))))
    form = UserChangeForm(request.POST or None, instance=customer)
    cart = Cart(request)
    cart_items = cart.__len__()

    if request.method == 'POST':
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
    
    context = {
        'title': 'customer details',
        'customer': customer,
        'cart_items': cart_items,
        'unpaid_orders': unpaid_orders,
        'total_unpaid_orders': total_unpaid_orders['total_unpaid'],
        'form': form,
    }
    return render(request, 'customer_detail_view.html', context)

# @login_required
# @permission_required("store.update_user", raise_exception=True)
# def update_customer(request, pk):
#     customer = get_object_or_404(User, pk=pk)
#     form = UserChangeForm(request.POST or None, instance=customer)

#     cart = Cart(request)
#     cart_items = cart.__len__()
#     # print(form)
    
#             return redirect('store:update_customer', pk=customer.pk)

store/views/error_handler_view.py
from django.shortcuts import render


def handler400(request, exception):
    return render(request, 'errors/400.html', status=400)


def handler403(request, exception):
    return render(request, 'errors/403.html', status=403)


def handler404(request, exception):
    return render(request, 'errors/404.html', status=404)


def handler500(request):
    return render(request, 'errors/500.html', status=500)

store/views/item_request_view.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import ItemRequest, Product
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from store.cartitem import Cart
# from django.db.models import Sum, F


@login_required
# @permission_required('store.view_itemrequest', raise_exception=True)
def item_request_view(request):
    item_request = ItemRequest.objects.all()

    cart = Cart(request)
    cart_items = cart.__len__()

    context = {
        'title': 'request items',
        'item_request': item_request,
        'cart_items': cart_items
    }
    return render(request, 'item_request_view.html', context)

@login_required
@require_POST
def request_item(request):
    if request.method == "POST":
        item_name = request.POST.get('itemName')
        message = request.POST.get('message')

        req = ItemRequest(
            request_by = request.user,
            item_name = item_name,
            message = message
        )
        req.save()
        return redirect('store:product_view')

@login_required
@require_POST
def request_product_restock(request, pk):
    product = get_object_or_404(Product, pk=pk)
    message = "Please restock this product. Thank you!"
    if request.method == "POST":
        req = ItemRequest(
            request_by = request.user,
            item_name = product.name,
            message = message
        )
        req.save()
        return redirect('store:product_view')

# @require_POST
# def noted_all_request(request):
#     all_request = ItemRequest.objects.filter(is_noted=False)
#     for req in all_request:
#         req.is_noted = True
#         print(req.is_noted)
#     # if request.method == "POST":
#     #     for req in all_request:
#     #         req.is_noted = True
#     #         print(req.is_noted)
#         # return redirect('store:product_view')

@login_required
@require_POST
@permission_required("store.update_itemrequest", raise_exception=True)
def request_status_update(request, pk):
    req = get_object_or_404(ItemRequest, pk=pk)
    print(req.is_noted)
    if request.method == "POST":
        req.is_noted = True
        print(req.is_noted)
        req.save()
        return redirect('store:product_view')
    

@login_required
def delete_request(request, pk):
    item_request = get_object_or_404(ItemRequest, pk=pk)
    print(item_request.request_by)
    if request.user.is_superuser or request.user == item_request.request_by:
        item_request.delete()
    else:
        messages.add_message(request, messages.DANGER, 'Access denied!')
    return redirect('store:product_view')

store/views/order_view.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import OrderTransaction, Customer
from django.contrib.auth.models import User
from store.cartitem import Cart
from django.views.decorators.http import require_POST
from django.db.models import Sum, Count, F, Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required

@login_required
@permission_required("store.view_ordertransaction", raise_exception=True)
def sales_view(request):
    orders = OrderTransaction.objects.all()
    paid_orders = OrderTransaction.objects.filter(Q(is_paid=True), Q(is_accepted=True)).aggregate(total=(Sum(F('price') * F('quantity'))))
    unpaid_orders = OrderTransaction.objects.filter(Q(is_paid=False), Q(is_accepted=True)).aggregate(total=(Sum(F('price') * F('quantity'))))
    cart = Cart(request)
    cart_items = cart.__len__()
    context = {
        "title": "sales",
        "orders": orders,
        "cart_items": cart_items,
        "paid_orders": paid_orders['total'],
        "unpaid_orders": unpaid_orders['total']
    }
    return render(request, 'sales_view.html', context)

@login_required
@permission_required("store.view_ordertransaction", raise_exception=True)
def sales_details(request, order_id):
    instance = get_object_or_404(OrderTransaction, order_id=order_id)

    cart = Cart(request)
    cart_items = cart.__len__()

    context = {
        'title': 'sales details',
        'instance': instance,
        'cart_items': cart_items,
    }
    return render(request, 'sales_details.html', context)

@login_required
def order_view(request):
    if request.user.is_superuser:
        orders = OrderTransaction.objects.all()
        balance = orders.filter(Q(is_paid=False) and Q(is_accepted=True)).aggregate(total=(Sum(F('price') * F('quantity'))))
    else:
        orders = OrderTransaction.objects.filter(customer=request.user)
        balance = orders.filter(Q(is_paid=False) and Q(is_accepted=True)).aggregate(total=(Sum(F('price') * F('quantity'))))
    cart = Cart(request)
    cart_items = cart.__len__()

    context = {
        "title": "orders",
        "orders": orders,
        "cart_items": cart_items,
        "balance": balance['total']
    }
    return render(request, 'order_view.html', context)

@login_required
@require_POST
@permission_required("store.update_ordertransaction", raise_exception=True)
def accept_order(request, order_id):
    instance = get_object_or_404(OrderTransaction, order_id=order_id)
    if request.method == 'POST':
        instance.is_accepted = True
        instance.save()
    messages.add_message(request, messages.SUCCESS, 'Order accepted.')
    return redirect('store:order_view')

@login_required
@require_POST
# @permission_required("store.update_ordertransaction", raise_exception=True)
def cancel_order(request, order_id):
    instance = get_object_or_404(OrderTransaction, order_id=order_id)
    if request.method == 'POST':
        instance.is_accepted = False
        instance.product.quantity += instance.quantity
        instance.product.save()
        instance.save()
        instance.delete()
    messages.add_message(request, messages.SUCCESS, 'Order cancelled.')
    return redirect('store:order_view')

@login_required
@require_POST
@permission_required("store.update_ordertransaction", raise_exception=True)
def pay_balance(request, pk):
    customer = get_object_or_404(User, pk=pk)
    unpaid_orders = OrderTransaction.objects.filter(customer=customer).filter(is_paid=False)
    if request.method == "POST":
        for instance in unpaid_orders:
            instance.is_paid = True
            instance.save()
            messages.add_message(request, messages.SUCCESS, '%s paid balance successfully. Thank you!'%(customer.username))
        return redirect('store:customer_details', customer.pk)

@login_required
@require_POST
@permission_required("store.update_ordertransaction", raise_exception=True)
def pay_order(request, order_id, *args, **kwargs):
    instance = get_object_or_404(OrderTransaction, order_id=order_id)
    if request.method == "POST":
        instance.is_paid = True
        instance.save()
        messages.add_message(request, messages.SUCCESS, 'Order paid successfully.')
        return redirect('store:customer_details', instance.customer.pk)

store/views/user_view.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib import messages

def register_user(request):
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.add_message(request, messages.SUCCESS, 'User successfully created name: %s.' % (instance.username.title()))
            return redirect('login')
    else:
        form = UserCreationForm(request.POST or None)
    context = {
        'title': 'registration',
        'form': form
    }
    return render(request, 'registration/register_user.html', context)

store/templates/add_product.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="col-sm-3">
        <div class="card border-0 shadow-sm mt-3">
            <div class="card-header">
                <strong>Add product</strong>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="add" class="btn btn-outline-primary btn-sm">
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-9">
        <div class="card border-0 shadow-sm mt-3">
            <div class="card-header">
                <strong>Products</strong>
            </div>
            <div class="card-body">
                <div class="row row-cols-1 row-cols-md-3 g-4">
                    {% for product in products %}
                    <div class="col">
                      <div class="card">
                        <!-- <img src="..." class="card-img-top" alt="..."> -->
                        <div class="card-body">
                          <h5 class="card-title">{{ product.name|title }}</h5>
                          <div class="row">
                            <div class="col-sm-6">
                                <div class="card border-primary">
                                    <div class="card-body p-1">
                                        <small>On stock:</small><br>
                                        <strong>{{ product.quantity }}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="card border-info">
                                    <div class="card-body p-1">
                                        <small>Price:</small><br>
                                        <strong>PHP {{ product.price }}</strong>
                                    </div>
                                </div>
                            </div>
                          </div>
                          {% if not product.quantity %}
                          <small class="text-muted">Out of stock, stocking soon!</small>
                          {% endif %}
                        </div>
                        <div class="card-footer pt-1 pb-1">
                            {% if product.quantity %}
                            <a href="{% url 'store:delete_product' product.pk %}" class="btn btn-outline-secondary btn-sm border-0 shadow-sm"><i class="fa-solid fa-trash-can"></i></a>
                            <a href="{% url 'store:delete_product' product.pk %}" class="btn btn-outline-secondary btn-sm border-0 shadow-sm"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a href="{% url 'store:add_order' product.pk %}" class="btn btn-outline-info btn-sm float-end border-0 shadow-sm">Add to <i class="fa-solid fa-cart-plus"></i></a>
                            {% else %}
                            <div>
                                <a href="{% url 'store:delete_product' product.pk %}" class="btn btn-outline-secondary btn-sm border-0 shadow-sm"><i class="fa-solid fa-trash-can"></i></a>
                                <a href="{% url 'store:add_order' product.pk %}" class="btn btn-outline-info btn-sm border-0 shadow-sm">Request</a>
                            </div>
                            {% endif %}
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
        </div>
        
    </div>
</div>


{% endblock %}

store/templates/customer_detail_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% if messages %}
  {% include 'includes/messages.html' %}
{% endif %}
<div class="row">
    <div class="col-sm-12 mt-3">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item" aria-current="page"><a href="{% url 'store:customer_view' %}">Customers</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{title|title}}</li>
        </ol>
      </nav>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card border-0 shadow-sm mt-3">
            <div class="card-header">
                <strong>{{title|title}}</strong>
                <a href="" class="btn btn-outline-primary btn-sm border-0 shadow-sm float-end" data-bs-toggle="modal" data-bs-target="#updateCustomer">Edit</a>
            </div>
            <div class="card-body">
                <h3>{{ customer.username|title }}</h3>
                <strong>Unpaid balance: PHP {% if total_unpaid_orders %}{{ total_unpaid_orders }}{% else %}0.0{% endif %}</strong>
                {% if unpaid_orders %}
                <div class="card border-0 mt-3">
                    <div class="card-header">
                        <strong>Order details</strong>
                    </div>
                    <div class="card-body">
                        
                        <table class="table table-sm" id="myTable">
                            <thead>
                                <tr>
                                  <th>Order number</th>
                                  <th>Date</th>
                                  <th>Particulars</th>
                                  <th>Price</th>
                                  <th>Quantity</th>
                                  <th>Total</th>
                                  <th>Status</th>
                                  <th>Pay</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in unpaid_orders %}
                                <tr>
                                  <td>{{ item.order_id }}</td>
                                  <td>{{ item.created|date }}</td>
                                  <td>{{ item.product.name }}</td>
                                  <td>{{ item.price }}</td>
                                  <td>{{ item.quantity }}</td>
                                  <td>{{ item.get_cost }}</td>
                                  <td>
                                    {% if item.is_paid %}
                                    Paid
                                    {% else %}
                                    Unpaid
                                    {% endif %}

                                  </td>
                                  <td>
                                    <form action="{% url 'store:pay_order' item.order_id %}" method="POST">
                                      {% csrf_token %}
                                      <input type="submit" value="Pay">
                                    </form>
                                  </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-outline-primary border-0 shadow-sm float-end" data-bs-toggle="modal" data-bs-target="#payBalance"><i class="fa-regular fa-money-bill-1"></i> Pay all</a>
                        <h3>Balance: PHP {% if total_unpaid_orders %}{{ total_unpaid_orders }}{% else %}0.0{% endif %}</h3>
                        
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="payBalance" tabindex="-1" aria-labelledby="payBalanceLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="payBalanceLabel">Pay balance</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'store:pay_balance' customer.pk %}" method="POST">
        {% csrf_token %}
        <div class="modal-body">
            Pay <strong>{{customer.name|title}}</strong> balance of <strong>PHP {{ total_unpaid_orders }}</strong>.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary border-0 shadow-sm" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-primary border-0 shadow-sm">Pay</button>
        </div>
        </form>
      </div>
    </div>
</div>

<div class="modal fade" id="updateCustomer" tabindex="-1" aria-labelledby="updateCustomerLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="updateCustomerLabel">Add customer</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="POST">
        {% csrf_token %}
        <div class="modal-body">
            {{form|crispy}}
            <!-- <input type="checkbox" class="form-control" name="contact" placeholder="Contact" value="{{customer.is_active}}"> -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary btn-sm border-0 shadow-sm" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-primary btn-sm border-0 shadow-sm">Update</button>
        </div>
        </form>
      </div>
    </div>
</div>
{% endblock %}

store/templates/pos_view.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  {% include 'includes/messages.html' %}
{% endif %}
<div class="row">
    <div class="col-sm-12">
        <div class="card border-0 shadow-sm mt-3">
            <div class="card-header">
                <strong><i class="fa-solid fa-cart-shopping"></i> Cart items</strong>
                {% if cart %}
                    <a href="{% url 'store:clear_order' %}" class="btn btn-outline-danger btn-sm border-0 shadow-sm float-end">Clear cart</a>
                {% endif %}
            </div>
            <div class="card-body">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>Particulars</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                            <tr>
                                <td>{{product.name|title}}</td>
                                <td>PHP {{product.price}}</td>
                                <td>
                                    <form action="{% url 'store:update_quantity' product.bar_code %}" method="post">
                                        {% csrf_token %}
                                        <div class="input-group">
                                            {% if not product.is_serial %}
                                            <input style="width: 40px;" value="{{ item.update_quantity_form.quantity }}" min="1" type="number" name="number" class="form-control form-control-sm" placeholder="Quantity" aria-label="quantity" aria-describedby="button-addon2">
                                            <button class="btn btn-outline-success btn-sm" type="submit" id="button-addon2">Update</button>
                                            {% else %}
                                            {{ item.update_quantity_form.quantity }}
                                            {% endif %}
                                        </div>
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url 'store:remove_cart_item' product.bar_code %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" title="Remove" class="btn btn-outline-danger btn-sm border-0 shadow-sm"><i class="fa-regular fa-trash-can"></i></button>
                                    </form>
                                </td>
                            </tr>
                            {% endwith %}
                        {% endfor %}
                    </tbody>
                </table>
                <div>
                    <h3>Total: PHP {{ cart.get_total_price  }}</h3>
                </div>
                {% if cart %}
                <form action="{% url 'store:process_order' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Confirm order" class="btn btn-primary border-0 shadow-sm mt-4">
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

store/templates/update_product_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
  <div class="col-sm-12 mt-3">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page"><a href="{% url 'store:product_view' %}">Products</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{title|title}}</li>
      </ol>
    </nav>
  </div>
</div>
  
<div class="row">
  <div class="col-sm-6">
      <div class="card border-0 shadow-sm mt-3">
        <div class="card-header">
            <strong>Products</strong>
        </div>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="card-body">
            {{form.name|as_crispy_field}}
            {{form.category|as_crispy_field}}
            {{form.image|as_crispy_field}}
            {{form.on_display|as_crispy_field}}
        </div>
        <div class="card-footer">
            <input type="submit" class="btn btn-outline-primary btn-sm" value="Update Product">
        </div>
        </form>
      </div>
  </div>
  <div class="col-sm-2">
    <div class="card mt-3">
      <div class="card-body">
        {% if product.image %}
        <img style="width: 100%; height: auto;" src="{{ product.image.url }}" alt="">
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}